ribbon:
  ReadTimeout: 200000
  ConnectTimeout: 200000
  ServerListRefreshInterval: 1000
  eureka:
    enabled: false

zuul:
  #ignoredServices: '*'
  #ignoreLocalService: false
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    AuthService:
      path: /login/**
      serviceId: AuthService
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
server:
  port: 8080


endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

micro:
  security:
    jwt:
      secret: otherpeopledontknowit

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: true
feign:
  hystrix:
    enabled: true
